apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: audioo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  audioo
    app.kubernetes.io/part-of: audioo  
  name: audioo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  audioo 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  audioo
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: audioo-model-config
        env:
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: model-key
              key: fd2ba1322c661acac8292c9cc28b72a8
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
