apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: audioo
  janus-idp.io/tekton: audioo
  backstage.io/kubernetes-id: audioo
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: audioo
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
