---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audioo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audioo 
  name: audioo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi