apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: audioo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audioo 
  name: audioo
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: audioo 
    weight: 100 
  wildcardPolicy: None
